services:
  postgres:
    shm_size: 1gb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c work_mem=256MB
      -c maintenance_work_mem=256MB
      -c temp_file_limit=10GB
      -c temp_buffers=64MB
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  postgres_data:
    driver: local
